[package]
name = "mcs4-fpga"
description = "FPGA synthesis support for MCS-4/MCS-40"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mcs4-core = { path = "../mcs4-core" }
mcs4-chips = { path = "../mcs4-chips" }
